version: "3.8"
# 2
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - hive-network

  communication-control:
    image: ${REGISTRY}/hiveemulator/communication-control:${TAG}
    ports:
      - "${COM_PORT:-8080}:8080"
    depends_on:
      - redis
    environment:
      - Redis__ConnectionString=redis:6379
    restart: unless-stopped
    networks:
      - hive-network

  map-client:
    image: ${REGISTRY}/hiveemulator/map-client:${TAG}
    ports:
      - "${MAP_PORT:-3000}:80"
    volumes:
      - ./config.json:/usr/share/nginx/html/config.json:ro
    depends_on:
      - communication-control
    restart: unless-stopped
    networks:
      - hive-network

  hive-mind:
    image: ${REGISTRY}/hiveemulator/hive-mind:${TAG}
    ports:
      - "${HIVE_PORT:-5149}:5149"
    depends_on:
      - redis
      - communication-control
    environment:
      - Redis__ConnectionString=redis:6379
      - CommunicationConfiguration__CommunicationControlIP=communication-control
    restart: unless-stopped
    networks:
      - hive-network

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
    networks:
      - hive-network

  node-exporter:
    image: prom/node-exporter:latest
    restart: unless-stopped
    networks:
      - hive-network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped
    networks:
      - hive-network

  loki:
    image: grafana/loki:2.9.0
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped
    networks:
      - hive-network

  promtail:
    image: grafana/promtail:2.9.0
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./monitoring/promtail.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    restart: unless-stopped
    networks:
      - hive-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "4000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped
    networks:
      - hive-network

networks:
  hive-network:
    driver: bridge