version: "3.8"

services:
  redis:
    image: redis:latest
    restart: unless-stopped
    networks:
      - hive-network

  communication-control:
    image: ${REGISTRY}/hiveemulator/communication-control:${TAG}
    ports:
      - "${COM_PORT}:8080"
    depends_on:
      - redis
    environment:
      - Redis__ConnectionString=redis:6379
    restart: unless-stopped
    networks:
      - hive-network

  map-client:
    image: ${REGISTRY}/hiveemulator/map-client:${TAG}
    ports:
      - "${MAP_PORT}:80"
    depends_on:
      - communication-control
    restart: unless-stopped
    networks:
      - hive-network

  hive-mind:
    image: ${REGISTRY}/hiveemulator/hive-mind:${TAG}
    ports:
      - "${HIVE_PORT}:5149"
    depends_on:
      - redis
      - communication-control
    environment:
      - Redis__ConnectionString=redis:6379
      - CommunicationConfiguration__CommunicationControlIP=communication-control
      - CommunicationConfiguration__CommunicationControlPort=8080
    restart: unless-stopped
    networks:
      - hive-network

networks:
  hive-network:
    driver: bridge